# Generated by Django 3.2.12 on 2022-03-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='complete_text',
            field=models.TextField(blank=True, help_text='Complete text of the book.', verbose_name='Raw Text'),
        ),
        migrations.AlterField(
            model_name='title',
            name='parsed_tokens',
            field=models.TextField(blank=True, help_text='Input tokens separated by a comma', verbose_name='Tokens'),
        ),
        migrations.AlterField(
            model_name='title',
            name='theme',
            field=models.CharField(blank=True, help_text='Input the theme associated to the book.', max_length=100, verbose_name='Theme'),
        ),
    ]
