# Generated by Django 3.2.12 on 2022-03-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_auto_20220314_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='vector_file',
            field=models.FileField(blank=True, help_text='Field to save a vector', null=True, upload_to='vectors_file'),
        ),
    ]
