# Generated by Django 3.2.12 on 2022-03-28 09:50

from django.db import migrations, models
import recommender.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_title_vector_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('index', models.FileField(blank=True, help_text='Insert the calculated index.', null=True, upload_to=recommender.models.upload_path)),
                ('new_index', models.FileField(blank=True, help_text='Insert the calculated new index.', null=True, upload_to=recommender.models.upload_path)),
                ('training_vectors', models.FileField(blank=True, help_text='Insert the calculated training_vectors.', null=True, upload_to=recommender.models.upload_path)),
                ('vocab_list', models.FileField(blank=True, help_text='Insert the calculated vocabulary list.', null=True, upload_to=recommender.models.upload_path)),
                ('topic_predictions', models.FileField(blank=True, help_text='Insert topic predictions csv', null=True, upload_to=recommender.models.upload_path)),
                ('training_book_ids', models.TextField(blank=True, help_text='Insert the book ids for this flow separated by a comma.')),
                ('ntm_predictor_endpoint', models.TextField(blank=True, help_text='Insert the NTM predictor endpoint.')),
                ('knn_predictor_endpoint', models.TextField(blank=True, help_text='Insert the KNN predictor endpoint.')),
                ('number_books', models.IntegerField(blank=True, default=0, help_text='Amount of books for this workflow.')),
                ('s3_paths', models.JSONField(blank=True, help_text='Field saved for a small dictionary of S3 paths.')),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
            },
        ),
        migrations.AddField(
            model_name='title',
            name='number_pages',
            field=models.IntegerField(default=0, help_text='Input the amount of pages of the book.', verbose_name='Number of pages'),
        ),
    ]
