# Generated by Django 3.2.12 on 2022-03-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_workflow_processing_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='processing_times',
            field=models.JSONField(blank=True, default=dict, help_text='Field saved for keeping track of time it take to process data.', null=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='s3_paths',
            field=models.JSONField(blank=True, help_text='Field saved for a small dictionary of S3 paths.', null=True),
        ),
    ]
