# Generated by Django 3.2.12 on 2022-03-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0006_auto_20220328_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='booklist',
            field=models.JSONField(blank=True, default=dict, help_text='List of books in the workflow.', null=True),
        ),
    ]
