# Generated by Django 3.2.12 on 2022-04-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0007_workflow_booklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='training_vectors',
            field=models.CharField(blank=True, help_text='Insert the local path of the calculated training_vectors.', max_length=255),
        ),
    ]
