# Generated by Django 3.2.12 on 2022-04-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0008_alter_workflow_training_vectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='training_book',
            field=models.BooleanField(default=False, help_text='Is the book used for training?', verbose_name='Is for training?'),
        ),
    ]
