# Generated by Django 3.2.12 on 2022-04-19 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0009_title_training_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='workflow',
            field=models.ForeignKey(blank=True, help_text='Select the workflow associated to this recommendation.', null=True, on_delete=django.db.models.deletion.CASCADE, to='recommender.workflow', verbose_name='Workflow'),
        ),
    ]
