# Generated by Django 3.2.12 on 2022-04-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0010_recommendation_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='cover',
            field=models.URLField(blank=True, help_text='Set the cover url', null=True, verbose_name='Cover'),
        ),
    ]
