# Generated by Django 3.2.12 on 2022-04-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0011_title_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='distance',
            field=models.CharField(blank=True, help_text='This represents the distance between vectors.', max_length=20, verbose_name='Distance'),
        ),
    ]
